# Generated by Django 4.0.6 on 2024-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_allow_negative_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_zero_ledgers',
            field=models.BooleanField(default=False),
        ),
    ]
