# Generated by Django 4.0.6 on 2024-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
