# Generated by Django 4.0.6 on 2024-08-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_cumulativeledger_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubLedgerTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prev_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountsubledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
