# Generated by Django 4.0.6 on 2024-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountsubledgertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubledgertracking',
            name='value_changed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
