# Generated by Django 4.0.6 on 2024-08-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountsubledgertracking_value_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeledger',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.tbljournalentry'),
        ),
    ]
